const champions = [
    {champion: "aatrox", image: "aatrox.png"},
    {champion: "ahri", image: "ahri.png"},
    {champion: "akali", image: "akali.png"},
    {champion: "akshan", image: "akshan.png"},
    {champion: "alistar", image: "alistar.jpg"},
    {champion: "amumu", image: "amumu.jpg"},
    {champion: "anivia", image: "anivia.png"},
    {champion: "annie", image: "annie.png"},
    {champion: "aphelios", image: "aphelios.webp"},
    {champion: "ashe", image: "ashe.png"},
    {champion: "aurelion sol", image: "aurelionSol.png"},
    {champion: "azir", image: "azir.png"},
    {champion: "bard", image: "bard.webp"},
    {champion: "blitzcrank", image: "blitzcrank.png"},
    {champion: "brand", image: "brand.png"},
    {champion: "braum", image: "braum.png"},
    {champion: "caitlyn", image: "caitlyn.png"},
    {champion: "camille", image: "camille.png"},
    {champion: "cassiopeia", image: "cassiopeia.png"},
    {champion: "chogath", image: "chogath.png"}, 
    {champion: "corki", image: "corki.webp"},
    {champion: "darius", image: "darius.png"},
    {champion: "diana", image: "diana.png"},
    {champion: "draven", image: "draven.png"},
    {champion: "dr mundo", image: "drMundo.png"},
    {champion: "ekko", image: "ekko.png"},
    {champion: "elise", image: "elise.png"},
    {champion: "evelynn", image: "evelynn.png"},
    {champion: "ezreal", image: "ezreal.png"},
    {champion: "fiddlesticks", image: "fiddlesticks.webp"},
    {champion: "fiora", image: "fiora.png"},
    {champion: "fizz", image: "fizz.png"},
    {champion: "galio", image: "galio.webp"},
    {champion: "gangplank", image: "gangplank.webp"},
    {champion: "garen", image: "garen.png"},
    {champion: "gnar", image: "gnar.webp"},
    {champion: "gragas", image: "gragas.png"},
    {champion: "graves", image: "graves.png"},
    {champion: "gwen", image: "gwen.webp"},
    {champion: "hecarim", image: "hecarim.png"},
    {champion: "heimerdinger", image: "heimerdinger.webp"},
    {champion: "illaoi", image: "illaoi.png"},
    {champion: "irelia", image: "irelia.webp"},
    {champion: "ivern", image: "ivern.png"},
    {champion: "janna", image: "janna.png"},
    {champion: "jarvan iv", image: "jarvan.webp"},
    {champion: "jax", image: "jax.webp"},
    {champion: "jayce", image: "jayce.png"},
    {champion: "jhin", image: "jhin.jpg"},
    {champion: "jinx", image: "jinx.webp"},
    {champion: "kaisa", image: "kaisa.jpg"},
    {champion: "kalista", image: "kalista.png"},
    {champion: "karma", image: "karma.webp"},
    {champion: "karthus", image: "karthus.webp"},
    {champion: "kassadin", image: "kassadin.png"},
    {champion: "katarina", image: "katarina.png"},
    {champion: "kayle", image: "kayle.png"},
    {champion: "kayn", image: "kayn.jpg"},
    {champion: "kennen", image: "kennen.png"},
    {champion: "khazix", image: "khazix.webp"},
    {champion: "kindred", image: "kindred.jpg"},
    {champion: "kled", image: "kled.webp"},
    {champion: "kogmaw", image: "kogmaw.jpg"},
    {champion: "leblanc", image: "leblanc.png"},
    {champion: "lee sin", image: "leeSin.webp"},
    {champion: "leona", image: "leona.png"},
    {champion: "lillia", image: "lillia.webp"},
    {champion: "lissandra", image: "lissandra.jpg"},
    {champion: "lucian", image: "lucian.png"},
    {champion: "lulu", image: "lulu.jpg"},
    {champion: "lux", image: "lux.png"},
    {champion: "malphite", image: "malphite.webp"},
    {champion: "malzahar", image: "malzahar.webp"},
    {champion: "maokai", image: "maokai.png"},
    {champion: "master yi", image: "masterYi.png"},
    {champion: "miss fortune", image: "missFortune.png"},
    {champion: "mordekaiser", image: "mordekaiser.jpg"},
    {champion: "morgana", image: "morgana.jpg"},
    {champion: "nami", image: "nami.png"},
    {champion: "nasus", image: "nasus.webp"},
    {champion: "nautilus", image: "nautilus.jpg"},
    {champion: "neeko", image: "neeko.png"},
    {champion: "nidalee", image: "nidalee.png"},
    {champion: "nocturne", image: "nocturne.png"},
    {champion: "nunu and willump", image: "nunu.webp"},
    {champion: "olaf", image: "olaf.png"},
    {champion: "orianna", image: "orianna.png"},
    {champion: "ornn", image: "ornn.png"},
    {champion: "pantheon", image: "pantheon.webp"},
    {champion: "poppy", image: "poppy.webp"},
    {champion: "pyke", image: "pyke.webp"},
    {champion: "qiyana", image: "qiyana.webp"},
    {champion: "quinn", image: "quinn.png"},
    {champion: "rakan", image: "rakan.png"},
    {champion: "rammus", image: "rammus.png"},
    {champion: "reksai", image: "reksai.png"},
    {champion: "rell", image: "rell.webp"},
    {champion: "renekton", image: "renekton.png"},
    {champion: "rengar", image: "rengar.png"},
    {champion: "riven", image: "riven.png"},
    {champion: "rumble", image: "rumble.webp"},
    {champion: "ryze", image: "ryze.png"},
    {champion: "samira", image: "samira.webp"},
    {champion: "sejuani", image: "sejuani.png"},
    {champion: "senna", image: "senna.jpg"},
    {champion: "seraphine", image: "seraphine.webp"},
    {champion: "sett", image: "sett.webp"},
    {champion: "shaco", image: "shaco.png"},
    {champion: "shen", image: "shen.png"},
    {champion: "shyvana", image: "shyvana.webp"},
    {champion: "singed", image: "singed.png"},
    {champion: "sion", image: "sion.png"},
    {champion: "sivir", image: "sivir.png"},
    {champion: "skarner", image: "skarner.png"},
    {champion: "sona", image: "sona.png"},
    {champion: "soraka", image: "soraka.png"},
    {champion: "swain", image: "swain.jpg"},
    {champion: "sylas", image: "sylas.png"},
    {champion: "syndra", image: "syndra.png"},
    {champion: "tahm kench", image: "tahmKench.webp"},
    {champion: "taliyah", image: "taliyah.jpg"},
    {champion: "talon", image: "talon.webp"},
    {champion: "taric", image: "taric.jpg"},
    {champion: "teemo", image: "teemo.png"},
    {champion: "thresh", image: "thresh.jpg"},
    {champion: "tristana", image: "tristana.jpg"},
    {champion: "trundle", image: "trundle.png"},
    {champion: "tryndamere", image: "tryndamere.jpg"},
    {champion: "twistedFate", image: "twistedFate.jpg"},
    {champion: "twitch", image: "twitch.webp"},
    {champion: "udyr", image: "udyr.jpg"},
    {champion: "urgot", image: "urgot.webp"},
    {champion: "varus", image: "varus.png"},
    {champion: "vayne", image: "vayne.png"},
    {champion: "veigar", image: "veigar.jpg"},
    {champion: "velkoz", image: "velkoz.jpg"},
    {champion: "vi", image: "vi.png"},
    {champion: "viego", image: "viego.webp"},
    {champion: "viktor", image: "viktor.png"},
    {champion: "vladimir", image: "vladimir.png"},
    {champion: "volibear", image: "volibear.png"},
    {champion: "warwick", image: "warwick.png"},
    {champion: "wukong", image: "wukong.png"},
    {champion: "xayah", image: "xayah.jpg"},
    {champion: "xerath", image: "xerath.png"},
    {champion: "xin zhao", image: "xinZhao.webp"},
    {champion: "yasuo", image: "yasuo.png"},
    {champion: "yone", image: "yone.webp"},
    {champion: "yorick", image: "yorick.webp"},
    {champion: "yuumi", image: "yuumi.png"},
    {champion: "zac", image: "zac.png"},
    {champion: "zed", image: "zed.png"},
    {champion: "ziggs", image: "ziggs.png"},
    {champion: "zilean", image: "zilean.png"},
    {champion: "zoe", image: "zoe.webp"},
    {champion: "zyra", image: "zyra.webp"}
]

const container = document.getElementById("container");
const searchBar = document.getElementById("search-bar");

champions.forEach(champ => {
    const card = document.createElement("div");
    card.classList.add("champions-card");
    card.setAttribute("id", champ.champion);
    container.appendChild(card);

    const img = document.createElement("img");
    img.src = `./champions/${champ.image}`;
    img.classList.add("champ-img");
    card.appendChild(img);
})

const championList = document.getElementsByClassName("champions-card");

searchBar.addEventListener("keyup", (event) => {
    let searchQueue = event.target.value.toLowerCase();

    for (let i = 0; i < championList.length; i++){
        if (!champions[i].champion.includes(searchQueue)){
            championList[i].style.display = "none";
        } else {
            championList[i].style.display = "block";
        }
    }
})